---
title: "01-intro_LCI"
author: "Jonathan Salo MD"
institute: "Levine Cancer Institute"
#date: "`r Sys.Date()`"
params:
  hide: FALSE
  show: FALSE
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
  pdf_document: default
  html_document: default
---
<style type="text/css">
.remark-slide-content {
    font-size: 32px;
    padding: 1em 4em 1em 4em;
    line-height: 1.6;
}
</style>

<!--- P10000266--->
<!--- Intro_02--->
I'm Dr Jonathan Salo, a  Cancer Surgeon at the Levine Cancer Institute.

If you’re seeing this video, it’s likely because you have an upcoming consultation scheduled.

You may have a recent diagnosis of cancer. Whatever your situation, we have a great team of people who can help you every step of the way.

???

notes here

---
[Link to Eso Dx Staging](02-Eso_Dx_Staging.html)


## Building

We’re in Building 2 of Levine Cancer Institute. If you’re using GPS, the traffic circle for patient dropoff is located at 1320 East Morehead Street.

The entrance to the building is on East Morehead Street between South Kings and Kenilworth.

---

# Address

A parking garage is right next door to the traffic circle.

If you need help with directions, please call us at (980) 442-6410

Our mailing address is 1021 Morehead Medical Drive, which is why you will find “1021” on the building.

---

Due to the Covid-19 pandemic, and our desire to
protect both our patients and staff, we no longer
allow visitors to accompany patients during their
visit.

However, we recognize how important it is to have
the support and assistance of family members
and friends, particularly if there is cancer
involved.

---

We do have several ways that we can make sure
that family members and friends can participate
in the initial consultation.

The first is that we can call a family member on
speakerphone during the consultation. You and I
and your family member will all be able to have a
conversation together.

---

Another option is a virtual visit, which is allows us
to have a video conference.

Another method is to use our virtual care portal,
which can be accessed at lci.doxy.me/salo. A
link is available in the comments section.
We have a webcam in the consultation room that
we can use for a video call with your family
member.

---

Alternatively, I can call a family member from my
office after the consultation to answer any of
their questions.

Please note that it can be difficult to get a good
cell phone signal in our garage. It may help to
park near the outside edge of the garage in
order to get a better signal.

---

During your consultation, we will review your case
and the information that has been collected so
far.

We may need to do a physical exam of your heart
and lungs, so please wear comfortable clothing.
I will provide you with my evaluation and make a
plan for the next steps

---

Those next steps may include:

- Additional xrays, such as a CT scan or PET scan
- An endoscopic procedure
- Placement of a feeding tube for nutrition if you
are having difficulty with eating
- Placement of a port for chemotherapy
- Scheduling for surgery
- Making a referral for chemotherapy or radiation
therapy

---

We recognize that a cancer diagnosis affects not
only the patient but the whole community of
family and friends. We have a lot of resources
to help patients and the people close to them.
- Support groups 
- Counseling to help with stress reduction
- Financial counselors and social workers to help
with insurance and other financial issues
- Supportive Oncology department to help with
managing symptoms

---

We have a full-time staff of **dietitians**

We have an **Integrative Oncology** program which
and can assist you in choosing supplements and
complementary therapies to help manage
symptoms and promote wellness without
interfering with your cancer treatment.

We have a **senior oncology clinic** which can help
with the special needs of our patients over age
75

---

I would also ask you to sign up for the **MyAtrium Health Portal**. 
This is a free and secure way for
you to communicate with your care team at
Atrium Health and the Levine Cancer Institute
With the portal, you can see when your upcoming
appointments are, and change your
appointments. You can review the information in
your medical records, including your provider’s
notes. Most importantly, you can send us
messages, which is the quickest way to reach
us.

---

The MyAtrium Health Portal can be accessed via a web browser on the desktop computer, and there is an app for either iphone or android

To sign up, go to myatriumhealth.org

There is a link below

To sign up, click New User. You will receive an activation text or email within 3 days

---


If you need help setting up your account, we have

support staff available Monday through Friday

8am to 5 pm at

• (704) 667-9145 or toll-free at

• (855) 799-0044

---

When you come for a consultation, please bring with you

• A list of your current medications

• A copy of your insurance cards

• List of your physicians

• Names and phone numbers of family members

that you want to participate in discussions about

your health care

Please also bring a list of any questions you may

have

I will look forward to meeting you.

---

If you have a new diagnosis of cancer, please check out one of the following videos

Feel free to subscribe so you can be notified about new videos

If there are video topics you would like us to cover, please leave a comment below.

